CREATE TABLE chorewars_chores (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER   
    REFERENCES chorewars_users(id) ON DELETE CASCADE NOT NULL,
  child_id INTEGER   
    REFERENCES chorewars_children(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  status BOOLEAN NOT NULL 
);